### ISSUE TITLE
Merging versus overwriting entries?

### ISSUE THREAD

**Issue by JasonMcMahan** [kpn-puppet/puppet-kpn-local_security_policy#2]
Good day, 
Thank you for the module and the ability to use name rather than sids that is helpful.

Is it possible to set whether entries in the lsp are merged versus over written?
For instance Logon as a service may have IIS entries for a web app, and i need to install an agent that also needs rights. It seems to over write and replace with that single entry.

Except for replace a process level token, but i think that is due to the failure/error
Error: /Stage[main]/Profile::agent/Local_security_policy[Replace a process level token
]: Could not evaluate: Execution of 'C:/Windows/system32/SecEdit.exe /configure /db c:\windows\temp\sdbimport-2018042410
2227.inf /cfg c:\windows\temp\infimport-20180424102227.inf' returned 3: Completed 1 percent (0/63)  Process Privilege Ri

The task has completed. Warnings occurred for some attributes during this operation. It's okay to ignore the warning.
See log %windir%\security\logs\scesrv.log for detail info.

Thank you

**Comment by rheijkoop** [comment]
Hi Jason,

Thanks for your question. 

I'm sure it can be done, but I am a little low on time.
I like your idea so I will get back to you on this.

Rob

**Comment by rheijkoop** [comment]
Hi Jason,

I have made a change so that you can use the option to merge privilege rights settings.
If you don't want to use 'merge' then the working stays the same.

'Privilege Rights' now supports merging of values (issue #2)
  - 'set:' will set the policy_value
  - 'merge:' will merge the policy_value
    '+' adds a value when using 'merge'
    '-' removes a value when using 'merge'

Rob
